import Head from 'next/head'
import Image from 'next/image'

import Home from '../components/Home'

export default function HomePage() {

  return (
    <div>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}