import Head from 'next/head'
import Image from 'next/image'

import { signIn, signOut, useSession, getSession } from "next-auth/client";

import Home from '../components/Home'

export default function HomePage() {

  return (
    <div>
      <Head>
        <title>Ruvits | Inicio</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}

export async function getServerSideProps(ctx) {
  return {
    props: {
      session: await getSession(ctx)
    }
  }
}