import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {
  Container,
  Button,
  Input,
  Spacer,
  Text,
  Link,
  Card,
  Grid
} from '@nextui-org/react';

// import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {

  // const { data: session } = useSession();

  // if (session) {

  //   return (

  //     <div className={styles.container}>

  //       Welcome user<br />

  //       <button onClick={() => signOut()}>Sign out</button>

  //     </div>

  //   );

  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className={styles.container}>

        Click to sign into your user account <br />

        <button onClick={() => signIn()}>Sign in</button>

      </div> */}
        
        <Grid.Container gap={2} justify="center">
          <Grid >
            <Text text="1 of 3">Column 1</Text>
            <Text text="1 of 3">Column 1</Text>
            <Text text="1 of 3">Column 1</Text>
            <Text text="1 of 3">Column 1</Text>
            <Text text="1 of 3">Column 1</Text>
            <Text text="1 of 3">Column 1</Text>
          </Grid>
          <Grid >
            <Text text="2 of 3">Column two</Text>
            <Text text="2 of 3">Column two</Text>
            <Text text="2 of 3">Column two</Text>
            <Text text="2 of 3">Column two</Text>
            <Text text="2 of 3">Column two</Text>
            <Text text="2 of 3">Column two</Text>
          </Grid>
        </Grid.Container>
      
    </div>
  );
}